<footer>
<div id="footer_block">
	<div id="footer">
		<p class="foot_left">
			<?php echo COPYRIGHT;?>
		</p>
		<p class="foot_right">
			<?php echo SACEM; ?>
		</p>
	</div>
	
	<div id="copyright">
	    <div id="sharing-action">
	    <a href="http://www.facebook.com/share.php?u=http://www.passanger.fr<?php print $_SERVER['REQUEST_URI'] ?>" id="fb-sharing-action" title="<?php print TITLE_SHARING_FB ?>"></a>
	    <a href="http://www.twitter.com/share?url=http://www.passanger.fr<?php print $_SERVER['REQUEST_URI'] ?>" id="twt-sharing-action" title="<?php print TITLE_SHARING_TWT ?>"></a>
	    <a href="https://plus.google.com/share?url=http://www.passanger.fr<?php print $_SERVER['REQUEST_URI'] ?>" id="glg-sharing-action" title="<?php print TITLE_SHARING_GGL ?>"></a>
	</div>
	</div>
	
</div>
</footer>
<div class="clear"></div>