<?php
	require_once 'class/Links.php';
	$links = new Links($pdo,$session->read('langue'));
	$linksInformation = $links->getAllLinks();
    $tag_langue = isset($_SESSION['langue'])?$_SESSION['langue']:'fr';
	$actual_url = ($_SERVER['REQUEST_URI'] == '/'?'/'.$tag_langue.'-home':$_SERVER['REQUEST_URI']);
?>
<header>
<div id="header_block">
	<div id="language">
		<a href="set_language.php?lang=en" title="English Version">
			<img src="public/media/image/flag_en.png" alt="Traduire en anglais"/>
		</a>
		<a href="set_language.php?lang=fr" title="Version Française">
			<img src="public/media/image/flag_fr.png" alt="Traduire en français"/>
		</a>
	</div>
	<div id="header">
		<ul>
		<?php
			foreach($linksInformation as $this_link_information){
				$id_css_array = explode('.',$this_link_information['href']);
				$id_css = reset($id_css_array);
				$url_tab = '/'.$tag_langue.'-'.$this_link_information['href'];
				
				if($this_link_information['href'] != 'home'){
					echo '
		<li '.(($actual_url == $url_tab)?'class="selected menu"':'class="menu"').' id="'.$id_css.'">
			<a href="'.$tag_langue.'-'.$this_link_information['href'].'#content-starting">'.
				$this_link_information['text'].'
			</a>
		</li>';
				
				}
			}
		?>
		</ul>
		
		<div id="box">
			<div id="rectangle">
			</div>
		</div>
	</div>
		
	<div id="logo">
		<a href="<?php echo $tag_langue; ?>-home">
			
		</a>
	</div>
</div>
</header>