<?php
	require_once 'class/Links.php';
	$links = new Links($pdo,$session->read('langue'));
	$linksInformation = $links->getAllLinks();
    $tag_langue = isset($_SESSION['langue'])?$_SESSION['langue']:'fr';
?>
<header>
	<div id="complement">
		<div id="language">
			<a href="set_language.php?lang=en" title="English Version">
				<img src="public/media/image/flag_en.png" />
			</a>
			<a href="set_language.php?lang=fr" title="Version Française">
				<img src="public/media/image/flag_fr.png" />
			</a>
		</div>
		<div id="header">
			<ul>
			<?php
				$cpt = 0;
				foreach($linksInformation as $this_link_information){
					$id_css_array = explode('.',$this_link_information['href']);
					$id_css = reset($id_css_array);
					
					echo '
			<li '.($cpt==0?'class="selected menu"':'class="menu"').'id="'.$id_css.'">
				<a href="'.$tag_langue.'-'.$this_link_information['href'].'">'.
					$this_link_information['text'].'
				</a>
			</li>';
					$cpt++;
				}
			?>
			</ul>
			
			<div id="box">
				<div id="rectangle">
				</div>
			</div>
		</div>
			
		<div id="logo">
			<a href="<?php echo $tag_langue; ?>-home">
				<img src="public/media/image/logo2.png" alt="logo" style="position: absolute;top:4px;left:25px"/>
			</a>
		</div>
	</div>
</header>