<?php
	require_once 'class/Links.php';
	$links = new Links($pdo,$session->read('langue'));
	$linksInformation = $links->getAllLinks();
        $tag_langue = isset($_SESSION['langue'])?$_SESSION['langue']:'fr';
?>
<header>
	<div id="complement">
		<div id="language">
			<a href="set_language.php?lang=en" title="English Version">
				<img src="public/media/image/flag_en.png" />
			</a>
			<a href="set_language.php?lang=fr" title="Version Française">
				<img src="public/media/image/flag_fr.png" />
			</a>
		</div>
		<div id="header">
			<?php
				foreach($linksInformation as $this_link_information){
					$id_css_array = explode('.',$this_link_information['href']);
					$id_css = reset($id_css_array);
					
					echo '
			<a href="'.$tag_langue.'-'.$this_link_information['href'].'">
				<div id="'.$id_css.'">'.
					$this_link_information['text'].'
				</div>
			</a>';
				}
			?>
		</div>
			
		<div id="logo">
		</div>
	</div>
</header>