<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<meta name="Description" content="<?php print $headerInformation['meta_description'] ?>" >
<meta name="Keywords" content="<?php print $headerInformation['meta_keywords'] ?>">
<meta name="Author" content="Passanger">
<meta NAME="Identifier-URL" CONTENT="">
<meta NAME="Date-Creation-yyyymmdd" content="20120726">
<meta name="Date-Revision-yyyymmdd" content="20120726">
<meta NAME="Reply-to" CONTENT="">
<meta NAME="revisit-after" CONTENT="15 days">
<meta NAME="Category" CONTENT="Internet">
<meta NAME="Publisher" CONTENT="Thibault DULON">
<meta NAME="Copyright" CONTENT="Thibault DULON">
<meta NAME="Generator" CONTENT="PHP Engineer, HTML5/CSS3 Integrator">
<meta NAME="robots" CONTENT="index, follow, all">
<meta name="Rating" content="general">
<meta name="Distribution" content="global">
<meta name="Geography" content="Paris, France, 75010">

<!-- Fav icone -->
<link rel="icon" type="image/png" href="public/img/favicon.png" />
<!--[if IE]>
    <link rel="shortcut icon" type="image/x-icon" href="public/img/favico.ico" />
<![endif]-->

<!-- REQUIRED CSS -->
<link rel="stylesheet" href="public/css/style.css" media="screen" type="text/css">
<link rel="stylesheet" href="public/css/animation.css" media="screen" type="text/css">
<!-- For scroll -->
<link rel="stylesheet" href="public/css/jScrollbar.jquery.css" type="text/css" />
<!-- For social transition -->
<link rel="stylesheet" type="text/css" href="public/css/common.css" />
<link rel="stylesheet" type="text/css" href="public/css/style2.css" />

<style type="text/css">
	body {
		margin:0px;
	}
	.jScrollbar3
	{margin:10px}
</style>
<!-- REQUIRED CSS IF BADASS IE -->
<!--[if lt IE 9]>
	<link rel="stylesheet" href="public/css/style_IE.css" media="screen" type="text/css">
<![endif]-->

<!-- Required script -->
<script type="text/javascript" src="public/js/jquery.js"></script>
<script type="text/javascript" src="public/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="public/js/jfunction.js"></script>
<script type="text/javascript" src="public/js/animation-background.js"></script>
<script type="text/javascript" src="public/js/function.js"></script>
<!-- For scroll -->       
<script type="text/javascript" src="public/js/jquery-ui.js"></script>        
<script type="text/javascript" src="public/js/jquery-mousewheel.js"></script>
<!-- For social transition -->
<script type="text/javascript" src="public/js/modernizr.custom.79639.js"></script> 
