<nav>
	<div class="perso1">
		<img src="public/media/image/perso1.png" alt="personnage1" width="25" height="140"/>
	</div>
	<div class="perso2">
		<img src="public/media/image/perso2.png" alt="personnage2" width="25" height="140"/>
	</div>
	<div class="perso3">
		<img src="public/media/image/perso3.png" alt="personnage3" width="25" height="140"/>
	</div>
	<div class="perso4">
		<img src="public/media/image/perso4.png" alt="personnage4" width="25" height="140"/>
	</div>
	
	<div class="cabine">
		<img src="public/media/image/cabine.png" alt="cabine" width="100"/>
	</div>
</nav>