<!-- For carousel -->
<script type="text/javascript" src="public/js/jquery.tmpl.min.js"></script>
<script type="text/javascript" src="public/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="public/js/jquery.elastislide.js"></script>
<script type="text/javascript" src="public/js/gallery.js"></script>
<noscript>
	<style>
		.es-carousel ul{
			display:block;
		}
	</style>
</noscript>
<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">	
	<div class="rg-image-wrapper">
		{{if itemsCount > 1}}
			<div class="rg-image-nav">
				<a href="#" class="rg-image-nav-prev">Previous Image</a>
				<a href="#" class="rg-image-nav-next">Next Image</a>
			</div>
		{{/if}}
		<div class="rg-image"></div>
		<div class="rg-loading"></div>
		<div class="rg-caption-wrapper">
			<div class="rg-caption" style="display:none;">
				<p></p>
			</div>
		</div>
	</div>
</script>

<div id="carousel-container">
    <div id="rg-gallery" class="rg-gallery">
	<div class="rg-thumbs">
	    <!-- Elastislide Carousel Thumbnail Viewer -->
	    <div class="es-carousel-wrapper">
		<div class="es-nav">
		    <span class="es-nav-prev">Previous</span>
		    <span class="es-nav-next">Next</span>
		</div>
		<div class="es-carousel">
		    <ul>
			<?php

			    foreach($the_album as $photo) {
			?>
			<li>
			    <a href="#">
				<img src="public/media/photo/<?php echo $target_album["dateAlbum"] . "/" . $photo["urlPhoto"]; ?>" data-large="" alt="<?php echo $photo["captionPhoto"]; ?>" data-description="<?php echo $photo["captionPhoto"]; ?>" />
			    </a>
			</li>
			<?php 
			    }
			?>
		    </ul>
		</div>
	    </div>
	    <!-- End Elastislide Carousel Thumbnail Viewer -->
	</div><!-- rg-thumbs -->
    </div><!-- rg-gallery -->
</div>